Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x761d6089da10>> (for post_run_cell), with arguments args (<ExecutionResult object at 761d6089f850, execution_count=7 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 761d6edffed0, raw_cell="import wandb
wandb.login()
run = wandb.init(
   .." store_history=True silent=False shell_futures=True cell_id=a78334a4-6b77-4df9-8eee-62053fe38f07> result=None>,),kwargs {}:
Error in callback <bound method _WandbInit._resume_backend of <wandb.sdk.wandb_init._WandbInit object at 0x761d6089da10>> (for pre_run_cell), with arguments args (<ExecutionInfo object at 761d518ed650, raw_cell="_jupyterlab_variableinspector_dict_list()" store_history=False silent=False shell_futures=True cell_id=None>,),kwargs {}:
Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x761d6089da10>> (for post_run_cell), with arguments args (<ExecutionResult object at 761d519fef10, execution_count=None error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 761d518ed650, raw_cell="_jupyterlab_variableinspector_dict_list()" store_history=False silent=False shell_futures=True cell_id=None> result='[]'>,),kwargs {}:
Error in callback <bound method _WandbInit._resume_backend of <wandb.sdk.wandb_init._WandbInit object at 0x761d6089da10>> (for pre_run_cell), with arguments args (<ExecutionInfo object at 761c9947bb90, raw_cell="
import json
import getpass
import hashlib
def im.." store_history=True silent=False shell_futures=True cell_id=None>,),kwargs {}:
Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x761d6089da10>> (for post_run_cell), with arguments args (<ExecutionResult object at 761c9949f910, execution_count=8 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 761c9947bb90, raw_cell="
import json
import getpass
import hashlib
def im.." store_history=True silent=False shell_futures=True cell_id=None> result='{"dataframes": [], "user": "aksavadogo"}'>,),kwargs {}:
Error in callback <bound method _WandbInit._resume_backend of <wandb.sdk.wandb_init._WandbInit object at 0x761d6089da10>> (for pre_run_cell), with arguments args (<ExecutionInfo object at 761c995df590, raw_cell="_jupyterlab_variableinspector_dict_list()" store_history=False silent=False shell_futures=True cell_id=None>,),kwargs {}:
Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x761d6089da10>> (for post_run_cell), with arguments args (<ExecutionResult object at 761ce68bf3d0, execution_count=None error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 761c995df590, raw_cell="_jupyterlab_variableinspector_dict_list()" store_history=False silent=False shell_futures=True cell_id=None> result='[]'>,),kwargs {}:
[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.login() after wandb.init() has no effect.
Error in callback <bound method _WandbInit._resume_backend of <wandb.sdk.wandb_init._WandbInit object at 0x761d6089da10>> (for pre_run_cell), with arguments args (<ExecutionInfo object at 761d6114cf90, raw_cell="import wandb
wandb.login()
run = wandb.init(
   .." store_history=True silent=False shell_futures=True cell_id=a78334a4-6b77-4df9-8eee-62053fe38f07>,),kwargs {}: